---
name: "Media Tags"
guid: "e6ee25c2-d12c-4382-a48c-77ee9c1c33cb"
version: "0.5.3.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "This plugin automatically adds Resolution and HDR tags to the media."
description: |
  "This plugin automatically scans the libraries and adds tags to the media items based on the properties of their video track. Media types covered are movies, tv shows / series and collections."
category: "General"
owner: "Thertzlor"
artifacts:
  - "Jellyfin.Plugin.MediaTags.dll"
changelog: '[" - "]'
